version: '3'
services:
   zoneminder:
    build:
      context: .
      args:
        - ZM_VERSION=1.31.1
    ports:
      - 8080:80
    # volumes:
    #   - ./config:/config
    #   - ./images:/var/cache/zoneminder/images
    #   - ./events:/var/cache/zoneminder/events
    environment:
      TZ: America/New_York
      