version: '3'
services:
   zoneminder:
    build:
      context: .
    ports:
      - 8080:80
    # volumes:
    #   - ./config:/config
    #   - ./images:/var/cache/zoneminder/images
    #   - ./events:/var/cache/zoneminder/events
    environment:
      MY_SQL_ROOT_PASSWORD: zmPassword
      TZ: America/New_York
      EMAIL_ADDRESS: youremailaddress@gmail.com
      EMAIL_PASSWORD: <<ENTER email password HERE>>
      SMTP_SERVER: "smtp.gmail.com:587"
      ROOT_SMTP_SERVER: "gmail.com"
